## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [36]:
a=[10, 20, 30]
print(a)

b = [30, 60, 90]
print(b)

[10, 20, 30]
[30, 60, 90]


In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [37]:
(a,b)


([10, 20, 30], [30, 60, 90])

In [38]:
print(a+b)


[10, 20, 30, 30, 60, 90]


In [51]:
whole_list = [10, 20, 30, 30, 60, 90] 
list_to_remove = [30]

final_list = (set(whole_list) - set(list_to_remove))
print(final_list)

#OR
a[:2]+b[1:]

{10, 20, 90, 60}


[10, 20, 60, 90]

In [62]:
C = [b - a for a, b in zip(a, b)]
print(C)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [72]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

Gsub= [sum(G[0]),sum(G[1]),sum(G[2]),sum(G[3])]
print(Gsub)

sum(Gsub)

[30, 32, 34, 34]


130

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [77]:
s = 'Now is the time for all good men to come to the aid of their country!'

#make it say 'all good countrymen'

In [93]:
split=s.split()
print(split)
split2=split[5 ]+" "+split[6 ]+ " "+split[15]+split[7]
print(split2)
final_split = split2.replace('!','')
print(final_split)

['Now', 'is', 'the', 'time', 'for', 'all', 'good', 'men', 'to', 'come', 'to', 'the', 'aid', 'of', 'their', 'country!']
all good country!men
all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [141]:
a = "Sarah earns $96500 in a year"
print(a)

split = a.split()
###NOT WORKING
salary = split[2].replace('$','')
timeframe=split.replace(['in','a','year'],'monthly', inplace=True)
print(salary)
print(timeframe)
salary=int(salary)
salary=salary/12
print(salary)
salary=str(salary)

split=str(split[:2])

split2 = split + '$' + salary + timeframe
print(split2)


Sarah earns $96500 in a year


AttributeError: 'list' object has no attribute 'replace'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [24]:
#Create one dictionary called CA and one called NY 
CA = {'name' : 'CA','pop density': 239.1,
      'race':{'Prop White':0.57,'Prop Afr Amer': .06,'Prop Asian':.13,'Prop Other':.22},
     'tenure':{'Owners':7035371,'Renters':5542127}}
NY = {'name' : 'NY','pop density': 411.2,
      'race':{'Prop White':0.65,'Prop Afr Amer': .15,'Prop Asian':.07,'Prop Other':.22},
     'tenure':{'Owners':3897837,'Renters':3419918}}

States={'CA':CA, 'NY':NY}

print(States)
print("\n")
#Check if Texas is in our state dictionary#
result = any('Texas' in States.values() for States in States.values())

print(result)
print("\n")
#Print the White population in New York as a percentage#
NYRace=(NY.get('race'))
NYWhites=(NYRace.get('Prop White'))
##now we have number, not percentage
percentage = "{:.0%}".format(NYWhites)
print(percentage)
print("\n")
#
#
#
#update the White population fraction of NY to 0.64, print %
CA2 = {'name' : 'CA','pop density': 239.1,
      'race':{'Prop White':0.57,'Prop Afr Amer': .06,'Prop Asian':.13,'Prop Other':.22},
     'tenure':{'Owners':7035371,'Renters':5542127}}
NY2 = {'name' : 'NY','pop density': 411.2,
      'race':{'Prop White':0.64,'Prop Afr Amer': .15,'Prop Asian':.07,'Prop Other':.22},
     'tenure':{'Owners':3897837,'Renters':3419918}}

States2={'CA2':CA2, 'NY2':NY2}

print("\n")
#Print the White population in New York as a percentage#
NYRace2=(NY2.get('race'))
NYWhites2=(NYRace2.get('Prop White'))
##now we have number, not percentage
percentage2 = "{:.0%}".format(NYWhites2)
print(percentage2)
print("\n")
#
#
#
#Print the percentage of households that are renters in California, with two decimal places
CA_housing=(CA.get('tenure'))
CA_owners=(CA_housing.get('Renters'))
CA_renters=(CA_housing.get('Owners'))
owners=int(CA_owners)
renters= int(CA_renters)
cahousing=owners+renters
rent_CA=renters/cahousing
perc_rent_CA = "{:.2%}".format(rent_CA)
print(perc_rent_CA)
#perc_2="{:0.2f}".format(perc_rent_CA)
#def printC(perc_rent_CA):
  #  print("\nYour Celsius value is {:0.2f}.\n".format(perc_rent_CA))
#printC(perc_rent_CA)

{'CA': {'name': 'CA', 'pop density': 239.1, 'race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}, 'NY': {'name': 'NY', 'pop density': 411.2, 'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}}


False


65%




64%


55.94%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [14]:
import numpy as np

#height, width = 4, 4
#num = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

#array = np.array(num).reshape((height, width))
#print(array)

a = np.full((4, 4), 3)
print(a)

#b=np.random.uniform((4,4),0,100)
#print(b)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [13]:
b=np.random.random((4, 4))
print(b)

[[0.61127799 0.31276897 0.21876677 0.24446383]
 [0.72232038 0.06225941 0.87081942 0.75033639]
 [0.0294859  0.96406554 0.38246775 0.89008662]
 [0.190082   0.32950166 0.23938881 0.37991636]]


In [15]:
c=a/b
print(c)

[[  4.90775072   9.59174422  13.71323427  12.27175421]
 [  4.15328169  48.18548671   3.44503112   3.99820671]
 [101.74354013   3.11182162   7.8437986    3.3704585 ]
 [ 15.78266254   9.10465818  12.5319143    7.89647493]]


In [23]:
#print the min, mean, max, median
print(c.min())
print(c.mean())
print(c.max())
median = np.median(c)
print(median)
perc90 = np.percentile(c,90)
print(perc90)

3.1118216214875676
16.35323865304087
101.74354013171086
8.500566553329477
31.984074625675028


In [26]:
#1. Compute and print the sum of the second column in `c`
c[:, 1].sum()

69.99371072431927