## Assignment 1 | Data Types 
Jason Wang <br>
2/6/22<br>


Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [11]:
a = [10,20,30]
b = [30,60,90]
print(a)
print(b)

[10, 20, 30]
[30, 60, 90]


In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [16]:
[a,b]

[[10, 20, 30], [30, 60, 90]]

In [15]:
a+b

[10, 20, 30, 30, 60, 90]

In [20]:
a[0:2]+b[1:3]

[10, 20, 60, 90]

In [29]:
index = 0
listylist =[]
for i in b:
    listylist.append(b[index] - a[index])
    index += 1
listylist

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [31]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
SumG = []
for list in G:
    SumG.append(sum(list))
SumG

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [32]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [54]:
s.split(" ")[5] + ' ' +  s.split(" ")[6] + ' ' + s.split(" ")[-1][0:-1] + s.split(" ")[7]

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [109]:
a = "Sarah earns $96500 in a year"

In [110]:
a[0:13] + str(round(float(a.split(' ')[2][1:])/12, 2)) + ' monthly'

'Sarah earns $8041.67 monthly'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [43]:
#Question 1
CA = {'Pop Density':239.1,'Prop White':0.57,'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22, 'Owners': 7035371, 'Renters': 5542127}
NY = {'Pop Density':411.2,'Prop White':0.65,'Prop Afr Amer': 0.15, 'Prop Asian': 0.07, 'Prop Other': 0.22, 'Owners': 3897837, 'Renters': 3419918}
states = {'California':CA, 'New York':NY, 'Texas': 'YEEEEEEEEEEEEEEEEHHHHHHHHHAAAAAAAAAAAAAAAAAAAAW'}

In [44]:
#Question 2
states['Texas']

'YEEEEEEEEEEEEEEEEHHHHHHHHHAAAAAAAAAAAAAAAAAAAAW'

In [46]:
#Question 3
states['New York']['Prop White']*100

65.0

In [47]:
#Question 4
states['New York']['Prop White'] = 0.64
states['New York']['Prop White']

0.64

In [51]:
#Question 5
round(states['California']['Renters']/(states['California']['Renters'] + states['California']['Owners']), 2)

0.44

import numpy as np### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [72]:
import numpy as np
import random 

In [111]:
#Question 1
a = np.tile(3,(4,4))
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [116]:
#Question 2
b = np.random.random((4,4))
b

array([[0.53034503, 0.37847948, 0.99056116, 0.89799875],
       [0.5548099 , 0.51675206, 0.53756762, 0.61791201],
       [0.51501241, 0.51014295, 0.03539198, 0.15637191],
       [0.64804636, 0.9135689 , 0.19450252, 0.76096655]])

In [117]:
#Question 3
c = a/b
c

array([[ 5.65669489,  7.92645346,  3.02858634,  3.34076188],
       [ 5.4072575 ,  5.80549205,  5.58069332,  4.85506016],
       [ 5.82510238,  5.88070466, 84.76496957, 19.18503161],
       [ 4.62929842,  3.28382457, 15.42396496,  3.9423546 ]])

In [127]:
#Question 4
print('min:', np.min(c))
print('mean:',np.mean(c))
print('max:', np.max(c))
print('median:', np.median(c))
print('90th percentile:', np.percentile(c,90))

min: 3.028586339755852
mean: 11.533515648429598
max: 84.76496957191787
median: 5.618694104157929
90th percentile: 17.304498286371956


In [130]:
#Question 4
print('sum of the second column is',sum(c)[1])

sum of the second column is 22.89647473840949
