## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
a = [10,20,30]
b = [30, 60,90]
print (a)
print (b)

[10, 20, 30]
[30, 60, 90]


In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [2]:
c =[a]+[b]
print (c)

[[10, 20, 30], [30, 60, 90]]


In [3]:
d = a+b
print (d)

[10, 20, 30, 30, 60, 90]


In [4]:
e = a+b
del e [2:4]
print (e)

[10, 20, 60, 90]


In [5]:
a = [10,20,30]
b = [30, 60,90]
difference = []
for num, item in zip(a,b):
    difference.append(item-num)
print(difference)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [6]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
add = [sum(G[0]), sum(G[1]), sum(G[2]), sum(G[3])]
print(add)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [7]:
s = 'Now is the time for all good men to come to the aid of their country!'
m=s.split(" ")
t=m[5:8]
u=m[15:]
v= t+u
order = [0, 1, 3, 2]
v = [v[i] for i in order]

stringList = ' '.join([str(item) for item in v ])
print(stringList.replace('!', ''))

all good country men


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [8]:
a = "Sarah earns $96500 in a year"
print(a.replace('$96500 in a year', '$8041.67 monthly'))

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [9]:
    CA_state = {'name': 'CA' , 'population density': '239.1', 'race':{'White':0.57, 'Afr Amer':0.06,'Asian':0.13,'Other':0.22}, 'tenure': {'Owners':7035371,'Renters':5542127}}
    NY_state = {'name': 'NY' , 'population density': '411.2', 'race':{'White':0.65, 'Afr Amer':0.15,'Asian':0.07,'Other':0.22}, 'tenure': {'Owners':3897837,'Renters':3419918}}
    
    states = {'CA':CA_state, 'NY':NY_state}
    print(states)

{'CA': {'name': 'CA', 'population density': '239.1', 'race': {'White': 0.57, 'Afr Amer': 0.06, 'Asian': 0.13, 'Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}, 'NY': {'name': 'NY', 'population density': '411.2', 'race': {'White': 0.65, 'Afr Amer': 0.15, 'Asian': 0.07, 'Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}}


In [10]:
print('Texas' in states)

False


In [11]:
 float(NY_state['race'] ['White']*100)

65.0

In [12]:
NY_state['race'] ['White']=0.64
NY_state

{'name': 'NY',
 'population density': '411.2',
 'race': {'White': 0.64, 'Afr Amer': 0.15, 'Asian': 0.07, 'Other': 0.22},
 'tenure': {'Owners': 3897837, 'Renters': 3419918}}

In [13]:
round((float (CA_state['tenure']['Renters']))/(float (CA_state['tenure']['Owners'] + CA_state['tenure']['Renters']))*100,2)

44.06

### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [14]:
import numpy as np
a = np.array([[3, 3, 3, 3]]*4)
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [15]:
b = np.random.randint([3, 5, 7, 9], [[10], [20], [30], [40]])
b

array([[ 4,  7,  7,  9],
       [11, 12, 18, 18],
       [14, 14,  7, 20],
       [22, 13, 36, 10]])

In [16]:
c=a/b
c

array([[0.75      , 0.42857143, 0.42857143, 0.33333333],
       [0.27272727, 0.25      , 0.16666667, 0.16666667],
       [0.21428571, 0.21428571, 0.42857143, 0.15      ],
       [0.13636364, 0.23076923, 0.08333333, 0.3       ]])

In [17]:
np.min(c)
np.mean(c)
np.max(c)
np.median(c)
print("Minimum of c is : ",end="")
print (np.min(c))
print("Mean of c is : ",end="")
print (np.mean(c))
print("Maximum of c is : ",end="")
print (np.max(c))
print("Median of c is : ",end="")
print (np.median(c))
print("90th percentile of c : ",
       np.percentile(c, 90))

Minimum of c is : 0.08333333333333333
Mean of c is : 0.2846341158841159
Maximum of c is : 0.75
Median of c is : 0.2403846153846154
90th percentile of c :  0.42857142857142855


In [18]:
second_column = c[:, [1]]
print(second_column)
np.sum(second_column)

[[0.42857143]
 [0.25      ]
 [0.21428571]
 [0.23076923]]


1.1236263736263736