## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [171]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

**Creating [[10, 20, 30], [30, 60, 90]]**

In [172]:
#trying it one way
[a] + [b]

[[10, 20, 30], [30, 60, 90]]

In [173]:
#trying it another way
c = [a, b]
print(c)

[[10, 20, 30], [30, 60, 90]]


In [174]:
#trying it a third way
e = [a]
e.extend([b])
print(e)

[[10, 20, 30], [30, 60, 90]]


**Creating [10, 20, 30, 30, 60, 90]**

In [175]:
#This way defines variable d as a concatenation of lists a and b.
d = a + b
print(d)

[10, 20, 30, 30, 60, 90]


In [176]:
#This way says insert 30 in index 4, 60 in index 5, and 90 in index 6 of list a.

a.insert(4, 30)
a.insert(5, 60)
a.insert(6, 90)
print(a)

[10, 20, 30, 30, 60, 90]


**Creating [10, 20, 60, 90]**

In [177]:
#delete the items at indices 2 and 3 (need to specify 2:4 because non-inclusive of upper boundary)
del a[2:4]
a

[10, 20, 60, 90]

**Creating [20, 40, 60]**

In [178]:
#telling it to delete the items at indices 2 and 3 and then add '40' at index 1

del a[0]
print(a)
del a[2]
print(a)
a.insert(1, 40)
print(a)

[20, 60, 90]
[20, 60]
[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [179]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
H = sum(G[0]), sum(G[1]), sum(G[2]), sum(G[3])
print(H)

(30, 32, 34, 34)


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [180]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [181]:
#tell me the index of the 'a' the beginning of 'all'
s.find('a')

20

In [182]:
#tell me the index for the 'n' at the end of 'men'
s.find('n')

31

In [183]:
#define variable t as the segment of string(s) that contains 'all good men'
t = s[20:32]
t

'all good men'

In [184]:
#modify variable t by replacing 'men' with 'countrymen'
t.replace('men', 'countrymen')

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [185]:
a = "Sarah earns $96500 in a year"
b = a.replace('$96500 in a year', '$8041.67 monthly')
b

'Sarah earns $8041.67 monthly'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [186]:
#create a dictionary named ca_dict with name as a string, pop_density as a float, and dictionaries for race and tenure
#create a dictionary named ny_dict with name as a string, pop_density as a float, and dictionaries for race and tenure
#create a dictionary named states with key-value pairs where California:ca_dict and New York:ny_dict

ca_dict = {'name': 'California', 'pop_density': 239.1, 'race': {'prop_white': 0.57, 'prop_afr_amer': 0.06, 'prop_asian': 0.13, 'prop_other': 0.22}, 'tenure': {'owners': 7035371, 'renters': 5542127}}
ny_dict = {'name': 'New York', 'pop_density': 411.2, 'race': {'prop_white': 0.65, 'prop_afr_amer': 0.15, 'prop_asian': 0.07, 'prop_other': 0.22}, 'tenure': {'owners': 3897837, 'renters': 3419918}}
states = {'California': ca_dict, 'New York': ny_dict}
print(states)

{'California': {'name': 'California', 'pop_density': 239.1, 'race': {'prop_white': 0.57, 'prop_afr_amer': 0.06, 'prop_asian': 0.13, 'prop_other': 0.22}, 'tenure': {'owners': 7035371, 'renters': 5542127}}, 'New York': {'name': 'New York', 'pop_density': 411.2, 'race': {'prop_white': 0.65, 'prop_afr_amer': 0.15, 'prop_asian': 0.07, 'prop_other': 0.22}, 'tenure': {'owners': 3897837, 'renters': 3419918}}}


In [187]:
#does not include Texas
print(states.keys())

dict_keys(['California', 'New York'])


In [188]:
#Ignore this, notes to self -- old code not using nested dictionaries to practice using zip command
#keys = ['name', 'pop_density', 'prop_white', 'prop_afr_amer', 'proper_asian', 'prop_other', 'owners', 'renters']
#ca_values = ['CA', 239.1, 0.57, 0.06, 0.13, 0.22, 7035371, 5542127]
#ca = dict(zip(keys, ca_values))
#ny_values = ['NY', 411.2, 0.65, 0.15, 0.07, 0.22, 3897837, 3419918] 
#ny = dict(zip(keys, ny_values))
#states = {'ca_dict':ca, 'ny_dict':ny}
#print(states)

In [189]:
#rounding NY prop_white to a percentage

for value in states["New York"]["race"].keys():
    states["New York"]['race'][value] = round(100 * states['New York']['race'][value],2)

print(states['New York']['race']['prop_white'])

65.0


In [190]:
#updating the White population fraction of NY to 0.64

states['New York']['race']['prop_white'] = 64.0
print(states['New York']['race']['prop_white'])

64.0


In [191]:
#calculated total number of ca households and then divided to find percentage that are renters. Then rounded perc_renters to two decimal spaces.
ca_households = states['California']['tenure']['renters'] + states['California']['tenure']['owners']
perc_renters = states['California']['tenure']['renters']/ca_households
print(perc_renters)
round(perc_renters, 2)

0.4406382732082327


0.44

### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [192]:
#created array a
import numpy as np
a = np.array([[[[3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3]]]])
print(a)

[[[[3 3 3 3]
   [3 3 3 3]
   [3 3 3 3]
   [3 3 3 3]]]]


In [193]:
#created array b 
b = np.random.rand(4,4)
print(b)

[[0.29999848 0.8831528  0.98119051 0.04513398]
 [0.51837543 0.24155739 0.96576368 0.57377303]
 [0.59458755 0.81247879 0.23238586 0.59211254]
 [0.95926383 0.07557972 0.31517089 0.43929965]]


In [194]:
#created array c by dividing a by b
c = a/b
print(c)

[[[[10.0000506   3.39692069  3.05751021 66.46876302]
   [ 5.7873113  12.41940865  3.10634998  5.22854832]
   [ 5.04551429  3.69240407 12.9095632   5.06660444]
   [ 3.12739821 39.69318968  9.5186457   6.82905159]]]]


In [195]:
#calculated descriptive statistics
np.min(c), np.max(c), np.mean(c), np.median(c), np.percentile(c, 90, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False,)

(3.057510206090252,
 66.46876302424062,
 12.209202122304099,
 5.50792981091703,
 26.30137644023428)

In [196]:
print(c)

[[[[10.0000506   3.39692069  3.05751021 66.46876302]
   [ 5.7873113  12.41940865  3.10634998  5.22854832]
   [ 5.04551429  3.69240407 12.9095632   5.06660444]
   [ 3.12739821 39.69318968  9.5186457   6.82905159]]]]


In [197]:
np.sum(c)

195.34723395686558

In [198]:
#I'm stuck on summing the second column. This just reprinted c :(
np.sum(c, axis=0)

array([[[10.0000506 ,  3.39692069,  3.05751021, 66.46876302],
        [ 5.7873113 , 12.41940865,  3.10634998,  5.22854832],
        [ 5.04551429,  3.69240407, 12.9095632 ,  5.06660444],
        [ 3.12739821, 39.69318968,  9.5186457 ,  6.82905159]]])