## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [ ]:
a = [10, 20, 30]

In [ ]:
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [ ]:
#1
a, b

In [ ]:
#2
a + b

In [ ]:
#3
del a[2]
del b[0]
a+b

In [ ]:
#4
a = list(range(20,80,20))
a

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [ ]:
G = [(13+9+8), (14+6+12), (10+13+11), (7+18+9)]
G

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [ ]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [ ]:
a = 'countrymen'
print (s[20:28],a)


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [ ]:
a = "Sarah earns $96500 in a year"
print(a.replace('$96500 in a year', "$8041.67 monthly"))


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [58]:
#1
states = {'CA' : {'Name': 'California', 'Population Density': 239.1},
          'NY' : {'Name': 'New York', 'Population Density' : 411.1}}

In [59]:
#1
states['CA']['Race'] = {'Prop White': .57, 'Prop Afr Amer': .06, 'Prop Asian': .13, 'Prop Other': .22}

In [60]:
#1
states['CA']['Tenure'] = {'Owners': 7035371, 'Renters': 5542127}

In [61]:
#1
states['NY']['Race'] = {'Prop White': .65, 'Prop Afr Amer': .15, 'Prop Asian': .07, 'Prop Other': .22}

In [62]:
#1
states['NY']['Tenure'] = {'Owners': 3897837, 'Renters': 3419918}

In [ ]:
#2
states('Texas')

In [63]:
#3
print(states['NY']['Race']['Prop White']*100,'%')

65.0 %


In [64]:
#4
states.update({'NY': {'Race' : {'Prop White': .64}}})

In [65]:
#4
print(states['NY']['Race']['Prop White']*100,'%')

64.0 %


In [66]:
#5
a = (states['CA']['Tenure']['Renters'])
print(a)

5542127


In [67]:
#5
b = (states['CA']['Tenure']['Owners'])
print(b)

7035371


In [70]:
#5
c = a+b

In [76]:
#5
print(round(a / c*100, 2),'%')

44.06 %


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [131]:
import numpy as np
from numpy import median

In [89]:
#1
a = np.zeros((4,4))
a[:] = 3
print(a)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [109]:
#2
b = np.random.uniform(size = (4,4), low = 0, high = 5)
print(b)

[[0.10109199 4.16309923 3.89078375 4.35006074]
 [4.89309171 3.99579282 2.30739681 3.90264588]
 [0.59137213 3.19960511 0.71676644 4.72334459]
 [2.60924161 2.0733097  1.32277806 3.87116845]]


In [115]:
#3
c = (a / b)
print(c)

[[29.67594251  0.72061698  0.77105287  0.68964554]
 [ 0.61310929  0.75078968  1.30016648  0.76870925]
 [ 5.0729479   0.93761571  4.18546383  0.63514316]
 [ 1.14975937  1.44696183  2.26795416  0.77495982]]


In [138]:
#4
print("min: ", c.min())
print("max: ", c.max())
print("mean: ", c.mean())
print("median: ", np.median(c))
print("90th percentile: ", np.percentile(c, 90))

min:  0.6131092930785168
max:  29.675942505873206
mean:  3.235052399322521
median:  0.8562877624579712
90th percentile:  4.629205865806364


In [150]:
#5
print(np.sum(c, axis=0))


[36.51175907  3.8559842   8.52463735  2.86845777]


In [152]:
#5
print(sum(c[:,1]))

3.8559841951726033
