## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10,20,30]

In [3]:
b = [30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [4]:
c = [a] + [b]
c

[[10, 20, 30], [30, 60, 90]]

In [5]:
c = a + b
c

[10, 20, 30, 30, 60, 90]

In [6]:
c = [a[0], a[1], b[1], b[2]]
c


[10, 20, 60, 90]

In [7]:
c = [a[1], a[0] + b[0], b[1]]
c 

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [8]:
G = [[13,9,8], [14,6,12], [10,13,11], [7,18,9]]
Fin1 = [sum(G[0]), sum(G[1]), sum(G[2]), sum(G[3])]
Fin1

Fin2 = []
for x in G:
    Fin2.append(sum(x))
Fin2

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [40]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [167]:
name = 'Braund, Mr. Owen Harris'
first_name = name.split('.')[1].lstrip().split(' ')[0] 
first_name 

'Owen'

In [80]:
#split = s.split(' ')
#try = s.split(' ')[1].

In [78]:
import re
s1 = s.strip('Now is the time for ')
s2 = s1.strip('!')
s3 = s2.split()
print(len(s3))
finstring = s3[0] + ' ' + s3[1] + ' ' + s3[10] + s3[2] 
finstring

11


'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [98]:
import re
a = "Sarah earns $96500 in a year"
a2 = re.sub("96500 in a year", "8041.67 monthly", a)
print(a2)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [29]:
CA = {'name': 'CA', 'pop_density': 239.1, 'race': {'pop_white': .57, 'pop_black': .06, 'pop_asian': .13, 'pop_other': .22}, 'tenure': {'owners': 7035371, 'renters': 5542127}}
NY = {'name': 'NY', 'pop_density': 411.2, 'race': {'pop_white': .65, 'pop_black': .15, 'pop_asian': .07, 'pop_other': .22}, 'tenure': {'owners': 3897837, 'renters': 3419918}}
states = {'CA': CA, 
          'NY': NY}
states


{'CA': {'name': 'CA',
  'pop_density': 239.1,
  'race': {'pop_white': 0.57,
   'pop_black': 0.06,
   'pop_asian': 0.13,
   'pop_other': 0.22},
  'tenure': {'owners': 7035371, 'renters': 5542127}},
 'NY': {'name': 'NY',
  'pop_density': 411.2,
  'race': {'pop_white': 0.65,
   'pop_black': 0.15,
   'pop_asian': 0.07,
   'pop_other': 0.22},
  'tenure': {'owners': 3897837, 'renters': 3419918}}}

In [37]:
print("Print None if Texas not in list :", states.get('TX'))
print('White Population NY Percentage : ', states['NY']['race']['pop_white'] * 100, '%')


Print None if Texas not in list : None
White Population NY Percentage :  65.0 %


In [40]:
states['NY']['race']['pop_white'] = .64
print('White Population NY Percentage : ', states['NY']['race']['pop_white'] * 100, '%')


White Population NY Percentage :  64.0 %


In [48]:
RentPercent = (states['CA']['tenure']['renters'])/(states['CA']['tenure']['owners'] + states['CA']['tenure']['renters']) * 100
RentPercent_2 = round(RentPercent, 2)
print('Percentage Households in CA that are renters :', RentPercent_2, '%')

Percentage Households in CA that are renters : 44.06 %


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [165]:
import numpy as np
#a = np.array(3)
a = np.tile(3,(4,4))
print(a)
b = np.random.random((4,4))
print(b)
c = a/b
print(c)

minC = c.min()
maxC = c.max()
meanC = c.mean()
medianC = np.median(c)
percentile90C = np.percentile(c, 90)
print("Min c :", minC)
print("Max c :", maxC)
print("Mean c :", meanC)
print("Median c :", medianC)
print("90th percentile c :", percentile90C)

column2_sum = c[:, 1].sum()
print("Sum of 2nd Column :", column2_sum)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
[[0.22902175 0.14640011 0.04852357 0.82723479]
 [0.23434969 0.78614422 0.26168825 0.22812563]
 [0.53418435 0.68290062 0.8458093  0.8958624 ]
 [0.36467486 0.50451103 0.60747026 0.57587107]]
[[13.09919251 20.49178737 61.8256227   3.62653994]
 [12.80138248  3.8160937  11.46402269 13.15064881]
 [ 5.61603877  4.39302573  3.54689881  3.34872856]
 [ 8.22650617  5.94635163  4.93851336  5.20949938]]
Min c : 3.3487285555300383
Max c : 61.8256226957618
Mean c : 11.343803288736146
Median c : 5.781195200754532
90th percentile c : 16.82121809346802
Sum of 2nd Column : 34.64725844077485
