## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
a = [10,20,30]
b = [30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [5]:
#1
print(a,b)

[10, 20, 30] [30, 60, 90]


In [8]:
#2
list_2 = a + b 
print(list_2)

[10, 20, 30, 30, 60, 90]


In [16]:
#3
print((a[:2])+ (b[1:]))

[10, 20, 60, 90]


In [18]:
#4
list_3 = [i * 2 for i in a]
print(list_3)


[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [39]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]


l_1 = sum(G[0])
l_2 = sum(G[1])
l_3 = sum(G[2])
l_4 = sum(G[3])


output = []
output = [l_1, l_2, l_3, l_4]
print(output)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [77]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [162]:
#selecting part of the sentence and turning a string into a list
part_1 = s[20:].strip('!').split()

#selecting parts of the list
part_2 = part_1[0:3]
part_3 = part_1[-1]

#joining part_2 and part_3
part_2.insert(2, part_3)

#turning a list into a string
part_4 = str.join(' ',part_2)

#"deleting" the space between words
part_4[:16]+part_4[17:]

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [175]:
a = "Sarah earns $96500 in a year"
a.replace('$96500', '$8041.67')[:20]+ " monthly"

'Sarah earns $8041.67 monthly'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [195]:
#1. Creating a dictionary - creating keys and value types for race and tenure
race_nyc = {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.07, 'Prop Other': 0.22}
race_ca = {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22}

tenure_nyc = {'Owners': 3897837, 'Renters': 3419918}
tenure_ca = {'Owners': 7035371, 'Renters': 5542127}

#1. Creating a dictionary - creating dictionary for each state
keys_ny = ['name', 'population density', 'race', 'tenure']
values_ny = ['NY', 411.2, race_nyc, tenure_nyc]
NY = dict(zip(keys_ny, values_ny))

keys_ca = ['name', 'population density', 'race', 'tenure']
values_ca = ['CA', 239.1, race_ca, tenure_ca]
CA = dict(zip(keys_ca, values_ca))

#1. Creating a dictionary - creating "states"
states = {'CA': CA, 'NY': NY}
print(states)

{'CA': {'name': 'CA', 'population density': 239.1, 'race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}, 'NY': {'name': 'NY', 'population density': 411.2, 'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}}


In [196]:
#2. Checking if Texas is in our state dictionary
'Texas' in states

False

In [197]:
#3 Printing the White population in New York as a percentage

b = NY['race']['Prop White']
percentage = "{:.0%}".format(b)
print(percentage)

65%


In [198]:
#4. Updating the White population fraction of NY to 0.64 and verifing

NY['race']['Prop White'] = 0.64
b = NY['race']['Prop White']
percentage = "{:.0%}".format(b)
print(percentage)


64%


In [210]:
#5. Printing the % of households that are renters in California, with two decimal places

renters_ca = CA['tenure']['Renters']
owners_ca = CA['tenure']['Owners']
tenure_ca = renters_ca + owners_ca
renters_ca_p = renters_ca/tenure_ca
renters_ca_p = "{:.2%}".format(renters_ca_p)
renters_ca_p

'44.06%'

### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [2]:
# Create and print a 4 x 4 array named a with value 3 everywhere.

import numpy as np
a = np.full((4, 4), 3)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [3]:
#2 Create and print a 4 x 4 array named b with elements drawn from a uniform random distribution 

import numpy as np
b = np.random.random((4, 4))
print(b)


[[0.04143232 0.72568324 0.53332934 0.39631537]
 [0.70764719 0.01653991 0.34303755 0.18218371]
 [0.88369773 0.27168578 0.09435266 0.84566727]
 [0.60749644 0.39046055 0.44172333 0.03089274]]


In [4]:
#3 Create and print array c by dividing a by b

c = a/b
print(c)

[[ 72.40724077   4.13403513   5.62504209   7.56972909]
 [  4.23940072 181.37943101   8.74539822  16.46689505]
 [  3.39482596  11.04216784  31.79560551   3.54749451]
 [  4.93830053   7.68323454   6.79158151  97.11018855]]


In [5]:
#4 Compute and print the min, mean, max, median, and 90th percentile values of c

import numpy as np

mean_c = np.mean(c)
min_c = np.min(c)
max_c = np.max(c)
median_c = np.median(c)
per_90_c = np.percentile(c,90)

print(mean_c, min_c, max_c, median_c, per_90_c)


29.17941068840691 3.394825964257896 181.37943100968232 7.626481814383719 84.75871465858242


In [316]:
# Compute and print the sum of the second column in c
column_sum = sum(c[:,1])
column_sum

22.956615210894434