## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [23]:
'''Creating list a'''
a = [item * 10 for item in range(1, 4)]

'''Creating list b'''
b = [item * 30 for item in range(1, 4)]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [24]:
'''Generating the 1st output'''
output1 = [a, b]
output1

[[10, 20, 30], [30, 60, 90]]

In [25]:
'''Generating the 2nd output'''
output2 = a + b
output2

[10, 20, 30, 30, 60, 90]

In [26]:
'''Generating the 3rd output'''
output3 = a[:2] + b[1:]
output3

[10, 20, 60, 90]

In [27]:
'''Generating the 4th output'''
output4 = [item * 2 for item in a]
output4

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [28]:
'''Creating list G'''
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

'''Creating the output'''
Output2 = [sum(lst) for lst in G]
Output2

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [29]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [30]:
'''Generating the expected result'''
Output3 = s[s.find('all'):s.find('all') + 4] + s[s.find('good'):s.find('good') + 5] + s[s.find('country'):s.find('country') + 7] + s[s.find('men'):s.find('men') + 3]
Output3

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [31]:
'''Defining the variable a'''
a = "Sarah earns $96500 in a year"

'''Generating the output'''
Output4 = a[:a.find('96500')] + str(round(float(a[a.find('96500'):a.find('96500') + 5]) / 12, 2)) + ' monthly'
Output4

'Sarah earns $8041.67 monthly'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [32]:
'''1. Creating the dictionary CA and NY'''    
CA = {'name':'CA', 
      'pop_density':239.1, 
      'race':{'White':0.57, 'Afr Amer':0.06, 'Asian':0.13, 'other':0.22}, 
      'tenure':{'owners':7035371, 'renters':5542127}}
NY = {'name':'NY', 
      'pop_density':411.2, 
      'race':{'White':0.65, 'Afr Amer':0.15, 'Asian':0.07, 'other':0.22}, 
      'tenure':{'owners':3897837, 'renters':3419918}}

'''Combining the two dictionaries'''
states = dict(zip(CA.keys(), [list(x) for x in zip(CA.values(), NY.values())]))

In [33]:
'''2. Checking if Texas is in our state dictionary '''    
print('TX' in states['name'])
print('Texas' in states['name'])

False
False


In [34]:
'''3. Print the White population in New York as a percentage'''
# Find the white population proportion
white_pop_ny = states['race'][states['name'].index('NY')]['White']
print('White population in New York is {}'.format(str(white_pop_ny * 100) + '%.'))

White population in New York is 65.0%.


In [35]:
'''4. Update the White population fraction of NY to 0.64'''
states['race'][states['name'].index('NY')]['White'] = 0.64
white_pop_ny = states['race'][states['name'].index('NY')]['White']
# Printing the updated percentage
print('White population in New York is now updated to {}'.format(str(white_pop_ny * 100) + '%.'))

White population in New York is now updated to 64.0%.


In [36]:
'''5. Print the percentage of households that are renters in California'''
# Find the number of renters in California
renter_ca = states['tenure'][states['name'].index('CA')]['renters']
# Find the number of households in California
hh_ca = sum(states['tenure'][states['name'].index('CA')].values())

# Printing the percentage
print('The percentage of renters is {}'.format(str(round(renter_ca / hh_ca * 100, 2)) + '%.'))

The percentage of renters is 44.06%.


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [37]:
'''Importing numpy'''
import numpy as np

'''Creating array a'''
a = np.ones((4, 4)) * 3
print(a)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [38]:
'''Creating array b'''
b = np.random.uniform(size = (4, 4))
print(b)

[[0.23036983 0.55363528 0.95294423 0.99612097]
 [0.93150131 0.27204349 0.19851236 0.86266693]
 [0.15694781 0.80231702 0.27836339 0.01765585]
 [0.19230074 0.15442722 0.55158604 0.63955463]]


In [39]:
'''Creating array c'''
c = a / b
print(c)

[[ 13.02253862   5.41872984   3.14813806   3.01168241]
 [  3.22060737  11.02764869  15.11240899   3.47758782]
 [ 19.1146344    3.73917033  10.77727938 169.91534817]
 [ 15.60056398  19.42662701   5.43886137   4.69076424]]


In [40]:
'''Compute and print the min, mean, max, median, and 90th percentile values of c'''
# min
print('min:\t{}'.format(c.min()))
# mean
print('mean:\t{}'.format(c.mean()))
# max
print('max:\t{}'.format(c.max()))
# median
print('median:\t{}'.format(np.median(c)))
# 90th percentile
print('90th:\t{}'.format(np.percentile(c, 90)))

min:	3.011682410549777
mean:	19.133911919373062
max:	169.91534816683034
median:	8.108070378459546
90th:	19.270630707602734


In [41]:
'''Compute and print the sum of the second column in c'''
print(sum(c[:, 1]))

39.612175881571034
