## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [4]:
[a, b]

[[10, 20, 30], [30, 60, 90]]

In [5]:
a + b

[10, 20, 30, 30, 60, 90]

In [15]:
list(filter((30).__ne__, a+b))

[10, 20, 60, 90]

In [18]:
[a[1], 40, b[1]]

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [44]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

In [45]:
sums = []
for i in range(len(G)):
    sums.insert(i, sum(G[i]))
sums

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [74]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [108]:
mylist = s.split(" ")
new = mylist[5:8]
new[2] = 'countrymen'
' '.join(new)

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [132]:
a = "Sarah earns $96500 in a year"

# Multiple steps method: 
alist = a.split(' ')
alist[2] = '$8041.67'
alist[5] = 'monthly' 
del alist[3:5]
' '.join(alist)

'Sarah earns $8041.67 monthly'

In [133]:
a = "Sarah earns $96500 in a year"

# One line method: 
a.replace('96500 in a year', '8041.67 monthly')

'Sarah earns $8041.67 monthly'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [83]:
# 1. Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, 
# race as a dictionary, and tenure for California and New York. 
CA = {'name': 'California', 'population density': 239.1, 
      'race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 
      'tenure': {'Owners': 7035371, 'Renters': 5542127}}

NY = {'name': 'New York', 'population density': 411.2, 
      'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 
      'tenure': {'Owners': 3897837, 'Renters': 3419918}}

# Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.
states = {'CA': CA, 'NY': NY}
states

{'CA': {'name': 'California',
  'population density': 239.1,
  'race': {'Prop White': 0.57,
   'Prop Afr Amer': 0.06,
   'Prop Asian': 0.13,
   'Prop Other': 0.22},
  'tenure': {'Owners': 7035371, 'Renters': 5542127}},
 'NY': {'name': 'New York',
  'population density': 411.2,
  'race': {'Prop White': 0.65,
   'Prop Afr Amer': 0.15,
   'Prop Asian': 0.07,
   'Prop Other': 0.22},
  'tenure': {'Owners': 3897837, 'Renters': 3419918}}}

In [77]:
# 2. Check if Texas is in our state dictionary 
result = any('Texas' in d.values() for d in states.values())
result 

False

In [82]:
# 3. Print the White population in New York as a percentage 
whiteprop_NY = states['NY']['race']['Prop White']
"{:.0%}".format(whiteprop_NY)

'65%'

In [84]:
# 4. Assume there was a typo in the data, and update the White population fraction of NY to 0.64.
states['NY']['race']['Prop White'] = 0.64

# Verify that it was updated by printing the percentage again. 
whiteprop_NY = states['NY']['race']['Prop White']
"{:.0%}".format(whiteprop_NY)

'64%'

In [90]:
# 5. Print the percentage of households that are renters in California, with two decimal places
renters_CA = states['CA']['tenure']['Renters']
rentersprop_CA = renters_CA / (renters_CA + states['CA']['tenure']['Owners'])
"{:.2%}".format(rentersprop_CA)

'44.06%'

### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [15]:
import numpy as np
a = np.repeat(3, 16).reshape(4,4)
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [19]:
b = np.random.uniform(0, 1, 16).reshape(4,4)
b

array([[0.01466758, 0.04912856, 0.90539129, 0.71491336],
       [0.76419182, 0.74993574, 0.95367346, 0.06180607],
       [0.35420157, 0.42552614, 0.11231774, 0.96227271],
       [0.0279248 , 0.53748169, 0.16352015, 0.64001509]])

In [20]:
c = np.divide(a, b) # (other method: c = a / b) 
c

array([[1.10193760e+01, 9.29555980e+00, 6.93781124e-01, 2.44700134e-02],
       [4.78926710e-01, 1.22569980e+00, 6.15956350e-01, 7.92909575e+00],
       [1.11454822e+00, 6.51037533e-02, 5.88383137e+00, 4.19279075e-01],
       [3.23704510e+01, 1.81729543e+00, 5.76826413e+00, 1.47503417e+00]])

In [35]:
print('The min of c is', np.min(c))
print('The mean of c is', np.mean(c))
print('The max of c is', np.max(c))
print('The median of c is', np.median(c))
print('The 90th percentile of c is', np.percentile(c, 90))

The min of c is 0.024470013411768306
The mean of c is 5.012292043598565
The max of c is 32.37045097591068
The median of c is 1.3503669815314319
The 90th percentile of c is 10.157467916340696


In [38]:
sum(c[:,1])

12.403658775181675