## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a=[10,20,30]
b=[30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [3]:
[a,b]

[[10, 20, 30], [30, 60, 90]]

In [4]:
a+b

[10, 20, 30, 30, 60, 90]

In [5]:
a[:2]+b[1:]

[10, 20, 60, 90]

In [15]:
z = (b-a for a, b in zip(a,b))

#or

try2=[b[0]-a[0],b[1]-a[1],b[2]-a[2]]
print(try2)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [26]:
G=[[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
new_list=[sum(G[0]),sum(G[1]),sum(G[2]),sum(G[3])]
print(new_list)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [27]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [48]:
i = s[20:28]+s[60:68]+s[29:32]
print(i)

#or

strippy=s.strip('!')
splitty=strippy.split()
new=splitty[5]+" "+splitty[6]+" "+splitty[15]+splitty[7]
print(new)

all good countrymen
all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [11]:
#step by step

a = 'Sarah earns $96500 in a year'

#way 1
b = a[:13]
c = int(a[13:18])
d = round((c/12),2)
e = ' monthly'
f = b+str(d)+e
print(f)

#one line

g = a[:13]+str(round((int(a[13:18])/12),2))+' monthly'
print(g)

#another way

##splitty=a.split()
##stripyear=splitty[2].strip('$')
##yearly=int(strippy)
##monthly=str(round((yearly/12),2))
##new=splitty[:2]+monthly
##print(new)

Sarah earns $8041.67 monthly
Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [21]:
#CaRace = {'Prop White':0.57,'Prop Afr Amer': .06,'Prop Asian':.13,'Prop Other':.22}
#CaTenure = {'Owners':7035371,'Renters':5542127}
CA = {'name' : 'CA','pop density': 239.1,
      'race':{'Prop White':0.57,'Prop Afr Amer': .06,'Prop Asian':.13,'Prop Other':.22},
     'tenure':{'Owners':7035371,'Renters':5542127}} 
NY = {'name':'NY','pop densiry':411.2,
     'race':{'Prop White':0.65,'Prop Afr Amer': .15,'Prop Asian':.07,'Prop Other':.22},
     'tenure':{'Owners':3897837,'Renters':3419918}}
#print(CA)
#print(NY)

states = {'CA':CA,'NY':NY}
print("1.")
print(states)
print()
print('2.')
print(states.keys())
print('                     ^ see no TX')
print()
print('3.')
NYRace=NY['race']
##print(NYRace['Prop White'])
print("{:.0%}".format(NYRace['Prop White']))
print()
print('4.')
PWup = {'Prop White':0.64}
NYRace.update(PWup)
print("{:.0%}".format(NYRace['Prop White']))
print()
print('5.')
CAten = (CA['tenure'])
print("{:.2%}".format(round(CAten['Renters']/(CAten['Renters']+CAten['Owners']),4)))


1.
{'CA': {'name': 'CA', 'pop density': 239.1, 'race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}, 'NY': {'name': 'NY', 'pop densiry': 411.2, 'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}}

2.
dict_keys(['CA', 'NY'])
                     ^ see no TX

3.
65%

4.
64%

5.
44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [12]:
import numpy
a = numpy.array([[3,3,3,3], [3,3,3,3],[3,3,3,3],[3,3,3,3]])
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [13]:
b = numpy.random.rand(4,4)
print(b)

[[0.18858103 0.71580353 0.02461958 0.11431178]
 [0.04044898 0.58812874 0.38811882 0.03452634]
 [0.24518453 0.66457798 0.37590861 0.10385236]
 [0.16576291 0.72603629 0.10845072 0.70912144]]


In [14]:
c = a/b
print(c)

[[ 15.9082806    4.19109419 121.8542297   26.24401356]
 [ 74.16750919   5.10092399   7.72959165  86.89019321]
 [ 12.23568219   4.51414296   7.98066308  28.88716257]
 [ 18.09813778   4.13202483  27.66233341   4.23058706]]


In [15]:
print(numpy.min(c))
print(numpy.max(c))
print(numpy.median(c))
print(numpy.percentile(c,90))

4.132024834390761
121.85422969586138
14.071981396877348
80.52885120081237


In [20]:
s=numpy.sum(c,axis=0)
print(s[1])

17.93818597861698
