## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
a= [10,20,30]
b= [30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [2]:
a[1]*2

40

In [3]:
print (a,b)
print  (a + b)
c=a[:2] 
d=b[:2]
print (c+d)
print (a[:2]+b[:2])
e= [a[0]*2,a[1]*2, a[2]*2]
print (e)

[10, 20, 30] [30, 60, 90]
[10, 20, 30, 30, 60, 90]
[10, 20, 30, 60]
[10, 20, 30, 60]
[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [4]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
G

[[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

In [5]:
x= G[0][0]+G[2][0]+G[3][0]
x
y=G[2][0]+G[2][0]+G[1][2]
y
z=G[1][0]+G[2][0]*2
z
list= [x,y,z,z]
list

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [6]:
s = 'Now is the time for all good men to come to the aid of their country!'
string=s[20:28]+s[60:68]+s[29:32]
string

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [7]:
a = "Sarah earns $96500 in a year"
a

'Sarah earns $96500 in a year'

In [8]:
a[0:13]

'Sarah earns $'

In [9]:
a[0:13] + str(round(float(a[13:18])-88458.33,2)) + a[21:]

'Sarah earns $8041.67 a year'

In [10]:
len(a)

28

In [11]:
type(a)

str

In [12]:
type(a[13:18])

str

In [13]:
num_float=float(a[13:18])-88458.33
num_float
j=round(num_float,2)
j
j_str=str(j)
j_str

'8041.67'

In [14]:
a[0:13] + j_str + a[21:]

'Sarah earns $8041.67 a year'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [15]:
CA_Race={'Prop_W':0.57,'Prop_AA':0.06,'Prop_As':.13,'Prop_O':.22}
CA_Tenure={'Own':7035371,'Rent':55421127}

In [16]:

CA={ 'Name':'California','Pop_Dens':239.1, 'CA_Race':{'Prop_W':0.57,'Prop_AA':0.06,'Prop_As':.13,'Prop_O':.22}, 'CA_Tenure':{'Own':7035371,'Rent':5542127}}

In [17]:
NY={ 'Name':'New York','Pop_Dens':411.2, 'NY_Race':{'Prop_W':0.65,'Prop_AA':0.15,'Prop_As':.07,'Prop_O':.22}, 'CA_Tenure':{'Own':3897837,'Rent':3419918}}

In [18]:
States= {'CA': CA, 'NY': NY}
States

{'CA': {'Name': 'California',
  'Pop_Dens': 239.1,
  'CA_Race': {'Prop_W': 0.57,
   'Prop_AA': 0.06,
   'Prop_As': 0.13,
   'Prop_O': 0.22},
  'CA_Tenure': {'Own': 7035371, 'Rent': 5542127}},
 'NY': {'Name': 'New York',
  'Pop_Dens': 411.2,
  'NY_Race': {'Prop_W': 0.65,
   'Prop_AA': 0.15,
   'Prop_As': 0.07,
   'Prop_O': 0.22},
  'CA_Tenure': {'Own': 3897837, 'Rent': 3419918}}}

In [19]:
States['CA']

{'Name': 'California',
 'Pop_Dens': 239.1,
 'CA_Race': {'Prop_W': 0.57, 'Prop_AA': 0.06, 'Prop_As': 0.13, 'Prop_O': 0.22},
 'CA_Tenure': {'Own': 7035371, 'Rent': 5542127}}

In [20]:
States['Texas']

KeyError: 'Texas'

In [21]:
print("{:.0%}".format(NY['NY_Race']['Prop_W']))

65%


In [22]:
NY['NY_Race']['Prop_W']=.64
print("{:.0%}".format(NY['NY_Race']['Prop_W']))

64%


In [23]:
X=CA['CA_Tenure']['Rent'] 
X


5542127

In [24]:
Y=CA['CA_Tenure']['Own']
Y

7035371

In [25]:
c=X + Y

In [26]:
X/c

0.4406382732082327

In [27]:
CA_Renters="{:.0%}".format(X/(X+Y))

In [28]:
print(CA_Renters)

44%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [29]:
import numpy as np

In [30]:
list= [3,3,3,3]
a=np.array([list, list, list, list])
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [31]:
list_r1=np.random.uniform(low=0.0, high=300, size=4)
list_r2=np.random.uniform(low=0.0, high=300, size=4)
list_r3=np.random.uniform(low=0.0, high=300, size=4)
list_r4=np.random.uniform(low=0.0, high=300, size=4)
b=np.array([list_r1, list_r2, list_r3, list_r4])
b

array([[ 80.60423761, 230.24682274, 158.12935481, 109.07052562],
       [  3.4358661 ,  38.69716514,  38.40072787, 188.14100967],
       [ 62.3830636 ,  21.85266708,  81.65232456, 178.30642167],
       [ 72.04988667, 284.64420587, 154.31047559, 169.27486503]])

In [32]:
c=np.array([list/list_r1, list/list_r2, list/list_r3, list/list_r4])
c

array([[0.03721889, 0.0130295 , 0.01897181, 0.02750514],
       [0.87314229, 0.07752506, 0.07812352, 0.01594549],
       [0.04808998, 0.13728301, 0.03674115, 0.01682497],
       [0.04163782, 0.01053947, 0.01944132, 0.01772265]])

In [33]:
np.min(c)

0.010539473272837073

In [34]:
np.max(c)

0.8731422914571837

In [35]:
np.median(c)

0.03212314278326278

In [36]:
np.percentile(c,90)

0.10770326655933055

In [37]:
float((list/list_r1)[1:2])+float((list/list_r2)[1:2])+float((list/list_r3)[1:2])+float((list/list_r4)[1:2])

0.2383770416988347

In [38]:
print('Min', np.min(c))
print('Max', np.max(c))
print('Median', np.median(c))
print('90th Percential', np.percentile(c,90))

Min 0.010539473272837073
Max 0.8731422914571837
Median 0.03212314278326278
90th Percential 0.10770326655933055


In [41]:
print("hello there")


hello there
