## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [13]:
a=[10,20,30]
b=[30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [14]:
#1
print([a],',',[b])
#OR
print([a]+[b])

[[10, 20, 30]] , [[30, 60, 90]]
[[10, 20, 30], [30, 60, 90]]


In [15]:
#2
print(a+b)

[10, 20, 30, 30, 60, 90]


In [23]:
#3
c=a.copy()
d=b.copy()
del c[2]
del d[0]
print(c+d)

[10, 20, 60, 90]


In [38]:
#4
e=[a[0]*2,a[1]*2,a[2]*2]
print (e)

#OR
d=[i*2 for i in a]
print (d)

[20, 40, 60]
[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [96]:
G= [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

H=[sum(G[0]),sum(G[1]),sum(G[2]),sum(G[3])]

print(H)

[30, 32, 34, 34]


In [103]:
import numpy as np
J = np.sum([[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]],axis=1)
listJ = J.tolist()
print(listJ)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [210]:
s = 'Now is the time for all good men to come to the aid of their country!'
v=s[:-1]
l=v.split()
print(l[5],l[6],l[-1]+l[7])

all good countrymen


In [328]:
#OR
s2='Now is the time for all good men to come to the aid of their country!'
print(s2[19:24]+s2[24:29]+s2[61:68]+s2[29:32])

 all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [294]:
a = "Sarah earns $96500 in a year"

print(a[:13],round(float(a[13:18])/12,2),'monthly')
#OR
print(a[:13] + str(round(float(a[13:18])/12,2)) + " monthly")


Sarah earns $ 8041.67 monthly
Sarah earns $8041.67 monthly


# Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [508]:
#1
raceprop = {1: {'white': 0.57, 'african american': 0.06, 'asian': 0.13,'other':0.22},
          2: {'white': 0.65, 'african american': 0.15, 'asian': 0.07,'other':0.22}}

tenure={1: {'owners':7035371 , 'renters': 5542127},
          2: {'owners':3897837 , 'renters': 3419918}}

CA= {'name': 'CA', 'Population Density': 239.1, 'race': raceprop[1],'tenure':tenure[1]}
NY={'name': 'NY', 'Population Density': 411.2, 'race': raceprop[2],'tenure':tenure[2]}

states={1:{'California':CA},
        2:{'New York':NY}}
states

{1: {'California': {'name': 'CA',
   'Population Density': 239.1,
   'race': {'white': 0.57,
    'african american': 0.06,
    'asian': 0.13,
    'other': 0.22},
   'tenure': {'owners': 7035371, 'renters': 5542127}}},
 2: {'New York': {'name': 'NY',
   'Population Density': 411.2,
   'race': {'white': 0.65,
    'african american': 0.15,
    'asian': 0.07,
    'other': 0.22},
   'tenure': {'owners': 3897837, 'renters': 3419918}}}}

In [516]:
#2
'Texas' in states

False

In [540]:
#3
print(NY['race']['white']*100,"%")
a_number=1/3

#print(states[2]['New York']['race']['white']*100,"%")

64.0 %


In [518]:
#4
NY['race']['white']=0.64
print(NY['race']['white']*100,"%")

64.0 %


In [537]:
CArenters=CA['tenure']['renters']
CAtotal=CArenters+CA['tenure']['owners']
print(round(CArenters/CAtotal*100,2),"%","of households in California are renters")


44.06 % of households in California are renters


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [417]:
a=np.full((4,4),3)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [362]:
b=np.random.uniform(-1,1,(4,4))
print(b)
#OR
#b2=np.full((4,4),np.random.uniform(-1,1,(4,4)))
#print(b2)

[[ 0.41057604  0.73154697 -0.69157453  0.08919919]
 [ 0.27664742 -0.2786524   0.11785532 -0.92664441]
 [-0.86611093  0.03158911 -0.6998489  -0.08653096]
 [ 0.96103884  0.34895508 -0.51352382  0.42707465]]


In [405]:
c=a/b
print(c)

[[  7.30680733   4.10089865  -4.33792723  33.63259408]
 [ 10.84412793 -10.7661016   25.45493994  -3.23748783]
 [ -3.46375956  94.96943895  -4.28663958 -34.66967237]
 [  3.12162203   8.59709511  -5.84198797   7.02453307]]


In [406]:
print("The minimum value of c is",round(c.min(),2))
print("The maximum value of c is",round(c.max(),2))
print("The median of c is",round(np.median(c),2))
print("The 90th percentile value of c is",round(np.percentile(c,90),2))

The minimum value of c is -34.67
The maximum value of c is 94.97
The median of c is 3.61
The 90th percentile value of c is 29.54


In [416]:
columsum=c[:,1].sum()
print("The sum of the 2nd column in c is",round(columsum,3))

The sum of the 2nd column in c is 96.901
