## Assignment 1 | Data Types

Add code cells as needed for your answers. 

In [13]:
import numpy as np

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [3]:
a = [10,20,30]
b = [30,60,90]
print(a)
print(b)

[10, 20, 30]
[30, 60, 90]


In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [5]:
c = [a,b]
print(c)

[[10, 20, 30], [30, 60, 90]]


In [6]:
d = a + b
print(d)

[10, 20, 30, 30, 60, 90]


In [9]:
e = a[:2] + b[1:3]
print(e)

[10, 20, 60, 90]


In [16]:
f = list(np.subtract(np.array(b),np.array(a)))
print(f)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [97]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
H = []
    
H = [sum(x) for x in G]    
print(H)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [43]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [59]:
s_mod = s[20:29] + s[61:68] + s[29:32]
print(s_mod)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [41]:
a = "Sarah earns $96500 in a year"
a_modified = a[:13] + str(8041.67) + " monthly"
print(a_modified)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [64]:
# 1
CA = {'name':'CA', 'pop_density':239.1, 'race':{'prop_white':0.57,'prop_afram':0.06, 'prop_asian': 0.13, 'prop_other':0.22}, 'tenure':{'owners':7035371, 'renters':5542127}}
NY = {'name':'NY', 'pop_density':411.2, 'race':{'prop_white':0.65,'prop_afram':0.15, 'prop_asian': 0.07, 'prop_other':0.22}, 'tenure':{'owners':3897837, 'renters':3419918}}

In [66]:
states = {'CA':CA,'NY':NY}

In [74]:
# 2
print(any('CA' in i.values() for i in states.values()))
print(any('TX' in i.values() for i in states.values()))

True
False


In [79]:
# 3
print(states.get('NY').get('race').get('prop_white')*100,"%")

65.0 %


In [81]:
# 4
states.get('NY').get('race').update({'prop_white':0.64})
print(states.get('NY').get('race').get('prop_white')*100,"%")

64.0 %


In [86]:
# 5
CA_renters = states.get('CA').get('tenure').get('renters')
CA_owners = states.get('CA').get('tenure').get('owners')
CA_rent_prop = CA_renters/(CA_renters + CA_owners)
CA_rent_pct = "{:.2%}".format(CA_rent_prop)

print(CA_rent_pct)

44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [94]:
# 1
a = np.full((4, 4), 3)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [103]:
# 2
b = np.random.rand(4,4)
print(b)

[[0.83670602 0.8442935  0.82230583 0.86342819]
 [0.39085356 0.71078075 0.16307573 0.23060044]
 [0.97589246 0.10669816 0.70624504 0.66425652]
 [0.85565624 0.47124941 0.15650492 0.42549187]]


In [104]:
# 3
c = a/b
print(c)

[[ 3.58548873  3.55326673  3.64827767  3.47452173]
 [ 7.67550892  4.2207108  18.39636062 13.00951565]
 [ 3.07410923 28.11669886  4.24781743  4.51632754]
 [ 3.5060809   6.36605568 19.16872651  7.05066348]]


In [112]:
# 4. Compute and print the min, mean, max, median, and 90th percentile values of `c`

print("The min of c is ",np.amin(c))
print("The mean of c is ",np.mean(c))
print("The max of c is ",np.amax(c))
print("The median of c is ",np.median(c))
print("The 90th percentile of c is ",np.percentile(c,90))

The min of c is  3.0741092262013154
The mean of c is  8.350633153362635
The max of c is  28.116698860850377
The median of c is  4.38207248170241
The 90th percentile of c is  18.782543564600633


In [115]:
# 5. Compute and print the sum of the second column in c
print(sum(c[:,1]))

42.256732066784
