## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [3]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [4]:
#add full list 'a' to list 'b'
[a]+[b]

[[10, 20, 30], [30, 60, 90]]

In [5]:
c = a + b 
c

[10, 20, 30, 30, 60, 90]

In [6]:
#delete '30' from value posistions 2 and 3, stop at 4
del c[2:4]
c

[10, 20, 60, 90]

In [7]:
#create a new list with values: a[1]:20, cast object to integers to perform math (add 10+30), b[1]:60 
new_list = [a[1],int((a[0]+b[0])),b[1]]
new_list

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [8]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

In [9]:
#Thank you google
[sum(G[0]),sum(G[1]),sum(G[2]),sum(G[3])]

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [10]:
#Potential code to use
#c.split(',')[0]
#b = str.split(a, ",")
#print('b = ', b)
#c = str.join(' ', b)

s = 'Now is the time for all good men to come to the aid of their country!'

In [11]:
#tried s.split(' ')[5] first, then added other values.
s.split(' ')[5] + s.split(' ')[6] + s.split(' ')[-1] + s.split(' ')[7]

'allgoodcountry!men'

In [12]:
#need to add ' ' between words!
s.split(' ')[5] + ' '+ s.split(' ')[6] + ' '+ s.split(' ')[-1] + s.split(' ')[7]

'all good country!men'

In [13]:
#How to get rid of '!' :words[-1][:-1]
s.split(' ')[5] + ' '+ s.split(' ')[6] + ' '+ s.split(' ')[-1][:-1] + s.split(' ')[7]

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [14]:
#Step 1
a = "Sarah earns $96500 in a year"
#Step 2: b = str.split(a, ",") to turn into mutable list
b = str.split(a, ' ')
b[2] = '$8041.67'
b[3] = 'monthly'
#Step 3: c = str.join(' ', b) and use c.split from above to manipulate string
c = str.join(' ', b)
c.split(' ')[0] + ' '+ c.split(' ')[1] + ' '+ c.split(' ')[2] + ' ' + c.split(' ')[3]

'Sarah earns $8041.67 monthly'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [15]:
    #1. Create dictionaries for CA and NY; Print them together as one dictionary "States"
CA = {'name' : 'CA','pop density': 239.1,
      'race':{'Prop White':0.57,'Prop Afr Amer': .06,'Prop Asian':.13,'Prop Other':.22},
      'tenure':{'Owners':7035371,'Renters':5542127}}

NY = {'name': 'NY', 'pop density': 411.2,
     'race':{'Prop White':0.65, 'Prop Afr Amer':.06, 'Prop Asian':.07, 'Prop Other':.22},
      'tenure':{'Owners':3897837,'Renters':3419918}}

States={'CA':CA, 'NY':NY}

print(States)

{'CA': {'name': 'CA', 'pop density': 239.1, 'race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}, 'NY': {'name': 'NY', 'pop density': 411.2, 'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}}


In [16]:
#2. Check if Texas is in our state dictionary
TX = 'Texas'
if TX in States:
    print ('Texas is in our state dictionary')
else: print('No Texans Here')

No Texans Here


In [17]:
#3.Print the White population in New York as a percentage

NYRace=(NY.get('race'))
NYWhites=(NYRace.get('Prop White'))
percentage = "{:.0%}".format(NYWhites)
print(percentage)

65%


In [18]:
#4. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. 
#Verify that it was updated by printing the percentage again.
#category.replace('thing you had’, ‘thing you want’) - tried this with NYWhites, but it was a float.
#tried to cast as an integer - failed, don't know why, because it worked below. 
#then tried to call the destination in the dictionary and try to change the number

NY['race']['Prop White'] = "{:.0%}".format(0.64)
print (NY)

{'name': 'NY', 'pop density': 411.2, 'race': {'Prop White': '64%', 'Prop Afr Amer': 0.06, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}


In [19]:
#5. Print the percentage of households that are renters in California, with two decimal places
renters = int(CA['tenure']['Renters'])
owners = int(CA['tenure']['Owners'])
housing = renters + owners
rent_CA = renters / housing
percent_rent = "{:.2%}".format(rent_CA)
print(percent_rent)

44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [20]:
import numpy as np

In [21]:
#1. Create and print a 4 x 4 array named a with value 3 everywhere.
a = np.full((4, 4), 3)
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [22]:
#2. Create and print a 4 x 4 array named b with elements drawn from a uniform random distribution
#Why doesn't np.random.uniform work?
b = np.random.randint (10, 90,(4,4))
b

array([[54, 23, 77, 14],
       [22, 74, 52, 83],
       [39, 42, 18, 86],
       [43, 59, 38, 79]])

In [23]:
#3. Create and print array c by dividing a by b
c = a/b
c

array([[0.05555556, 0.13043478, 0.03896104, 0.21428571],
       [0.13636364, 0.04054054, 0.05769231, 0.03614458],
       [0.07692308, 0.07142857, 0.16666667, 0.03488372],
       [0.06976744, 0.05084746, 0.07894737, 0.03797468]])

In [24]:
print (c.min())
print (c.mean())
print (c.max())
print (np.median(c))
p_90 = np.percentile(c, 90)
print (p_90)

0.03488372093023256
0.08108857135763936
0.21428571428571427
0.0637298747763864
0.1515151515151515


In [25]:
#5. Sum column 2 in C
column_sum = c[:, 1].sum()
column_sum

0.29325135220492626